print("Hi, my name is RudeAI.")
print("I'd like to ask you a few qestions.")
human = input("What is your name? ")
print(human, "?!!! Why would anyone name a baby that?")
Year = int(input("How old are you?"))
print("Ooooo!!! " , Year, "is getting up there.")
num1 = input("What do you do for fun?")
print("I throught only nerds like to", num1, "?")
num2 = input("What kind of music to you like?")
print("Boooo!!! I wouldn't wish the sound of " , num2, " on my worst enemy.")
num3 = input("How many siblings do you have?")
print(num3, "? Wow, I hope the rest of your family is better looking.")
num4 = input("What do you want to be when you grow up?")
print("I think you'd have to be smarter to be a ", num4, ".")
print("So ", human, ", you're ", Year, "...")
print("You like to ", num1, " and listen to ", num2, "...")
print("Good luck becoming a ", num4, ".")
print("I'm only kiddn' ", human, ".")
